---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-app
  namespace: {{.Values.metadata.argocd_app_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{.Values.metadata.instana_provider_namespace}}
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
        - /spec/source/repoURL
      kind: Application
  project: default
  source:
    path: config/crossplane
    repoURL: {{.Values.repoURL}}
    directory:
      jsonnet: {}
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
