---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-app
  namespace: {{.Values.metadata.argocd_app_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: {{.Values.metadata.crossplane_namespace}}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.4.1
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    jsonPointers:
    - /rules
    kind: ClusterRole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
